from web.routes.blog_list import blog_list
from web.routes.blog import blog
from web.routes.direct_message import direct_message
from web.routes.friend_list import friend_list
from web.routes.index import index
from web.routes.login import login
from web.routes.logout import logout
from web.routes.message_poll import message_poll
from web.routes.register import register
from web.routes.search import search
from web.routes.user_list import user_list
from web.routes.user_preferences import user_preferences
from web.routes.user_profile import user_profile
from web.routes.new_blog import new_blog
from web.routes.notifications import notifications
from web.routes.random_user import random_user
from web.routes.add_friend import add_friend
from web.routes.remove_friend import remove_friend
from web.routes.konata import konata
from web.routes.news import news
from web.routes.message_list import message_list
from web.routes.set_timezone import set_timezone