errors:
  validation:
    missing_input: "{0} is required"
    invalid_email: "please enter a valid email address"
    email_taken: "that email is already in use"
    password_mismatch: "passwords do not match"
    auth_failure: "login details are incorrect"
    bad_length: "{0} must be between {1} and {2} characters long"

